main/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('write', views.write, name='write'),
    path('about', views.about, name='about'),
    path('story1', views.story1, name='story1'),
    path('edit', views.edit, name='edit'),
    path('matkul', views.matkul, name='matkul'),
    path('success', views.success, name='success'),
    path('delete', views.delete, name='delete'),
    #path('detail', views.detail, name='detail'),
    url(r'^detail/$', views.detail ),
    path('tambahkegiatan', views.tambahkegiatan, name='tambahkegiatan'),
    path('kegiatan', views.kegiatan, name='kegiatan'),
    path('daftar/<int:id>', views.daftar, name='daftar'),
    
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    matkul_name = models.CharField(max_length=50)
    lecturer_name = models.CharField(max_length=50)
    sks = models.IntegerField()
    matkul_desc =  models.TextField(max_length=100)
    acad_year = models.CharField(max_length=50)
    room = models.CharField(max_length=10)

class Delete(models.Model):
    del_name = models.CharField(max_length=50)

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=50)
    deskripsi_kegiatan = models.TextField(max_length=100)
    def __str__(self):
        return self.nama_kegiatan

class Orang(models.Model):
    nama_kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    nama_orang = models.CharField(max_length=50)
    def __str__(self):
        return self.nama_orang

main/forms.py
from django import forms
from .models import Matkul, Delete, Kegiatan, Orang
from django.forms import ModelForm
class MatkulForm(ModelForm):
    class Meta:
        model = Matkul
        fields = '__all__'

class DeleteForm(ModelForm):
    class Meta:
        model = Delete
        fields = '__all__'

class KegiatanForm(ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"

class OrangForm(ModelForm):
    class Meta:
        model = Orang
        fields = ["nama_orang"]

main/views.py
from django.shortcuts import render, redirect
from .forms import MatkulForm, DeleteForm, KegiatanForm, OrangForm
from django.http import HttpResponse, HttpResponseRedirect
from .models import Matkul, Delete, Kegiatan, Orang

# Create your views here.
def index(request):
    
    return render(request, 'main/index.html')
def write(request):
    return render(request, 'main/write.html')
def about(request):
    return render(request, 'main/about.html')
def story1(request):
    return render(request, 'main/story1.html')
def edit(request):
    if(request.method == 'POST' ):
        form = MatkulForm(request.POST)
        if(form.is_valid()):
            
            name = form.cleaned_data['matkul_name']
            lecturer = form.cleaned_data['lecturer_name']
            sks = form.cleaned_data['sks']
            year = form.cleaned_data['acad_year']
            desc = form.cleaned_data['matkul_desc']
            room = form.cleaned_data['room']
            p = Matkul(matkul_name=name, lecturer_name=lecturer, sks=sks, acad_year=year, matkul_desc=desc, room=room)
            p.save()
            return HttpResponseRedirect('/success')
    else:
        form = MatkulForm
    context = {'form' : form}
    return render(request, 'main/editmatkul.html', context)

def matkul(request):
    matkullist=Matkul.objects.all().values()
    return render(request, 'main/matkul.html', {'matkullist':matkullist})

def success(request):
    return render(request, 'main/success.html')

def delete(request):
    if(request.method == 'POST' ):
        form = DeleteForm(request.POST)
        if(form.is_valid()):
            name_tobe_del = form.cleaned_data['del_name']
            id_tobe_del = 0
            for dc in Matkul.objects.all().values():
                if dc.get("matkul_name").strip().lower() == name_tobe_del.strip().lower():
                    id_tobe_del = dc.get("id")

            if id_tobe_del != 0:
                Matkul.objects.filter(id=id_tobe_del).delete() 
            return HttpResponseRedirect('/success')
    else:
        form = DeleteForm
    context = {'form' : form}
    return render(request, 'main/delete.html', context)



def detail(request):
    if request.method=='GET':
        iid = request.GET.get('id')
        m=""
        d=""
        for dc in Matkul.objects.all().values():
                if int(dc.get("id")) == int(iid):
                    d = dc.get("matkul_desc")
                    m = dc.get("matkul_name")
        # if not m:
        #     return render(request, 'another.html')
        
        return render(request, 'main/detail.html', {'m':m, 'd':d})

def tambahkegiatan(request):
    if(request.method == "POST"):
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/success')
    else:
        form = KegiatanForm()
    context = {'form' : form}
    return render(request, "main/tambahkegiatan.html", context)

def kegiatan(request):
    orang = Orang.objects.all()
    kegiatan = Kegiatan.objects.all()
    context = {"orang":orang, "kegiatan":kegiatan}
    return render(request, 'main/kegiatan.html', context)

def daftar(request, id):
    if(request.method == "POST"):
        form = OrangForm(request.POST)
        if form.is_valid():
            kegiatan = Kegiatan.objects.get(id=id)
            orang = form.cleaned_data["nama_orang"]
            form = Orang(nama_kegiatan = kegiatan, nama_orang=orang)
            form.save()
            return HttpResponseRedirect('/success')
    else:
        form = OrangForm()
    context = {'form' : form}
    return render(request, "main/daftar.html", context)

main/templates/footer.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">
    <footer class="page-footer black">
		<ul>
	<li><a href="https://www.instagram.com/aziz_js/"><i class="fab fa-instagram"></i></a></li>
	<li><a href="https://twitter.com/azizjabbar_s"><i class="fab fa-twitter"></i></a></li>
	<li><a href="https://web.facebook.com/aziz.jabbarshiddiq"><i class="fab fa-facebook"></i></a></li>
	<li><a href="https://www.linkedin.com/in/aziz-jabbar-178360194/"><i class="fab fa-linkedin"></i></a></li>
	</ul>
		</footer>
		
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/about.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">

	{% include "navbar.html" %} 
    <div class="container" style="margin-top: 50px;">
        <h1>Lorem Ipsum</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
             ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
             laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in 
             voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat 
             cupidatat non proident, 
            sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    
		{% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/another.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">

	{% include "navbar.html" %} 
    <div class="container" style="margin-top: 50px;">
        <h1>Lorem Ipsum</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
             ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
             laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in 
             voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat 
             cupidatat non proident, 
            sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    
		{% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/daftar.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">

	{% include "navbar.html" %} 
    <div class="container" style="margin-top: 50px;" >
        <h2 align='center'>Daftar</h2>
        <form action="#" method="post">
            {% csrf_token %}
            <table align="center">
            {{ form.as_table }}
            </table>
            <p align="center"><input type="submit" value="OK" ></p>
        </form>
    </div>
	{% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/delete.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">

    {% include "navbar.html" %}
    <div class="container" style="margin-top: 50px;">
    <h2 align="center">Hapus Matkul</h2>
    <form action="/delete" method="post">
        {% csrf_token %}
        <table align="center">
        {{ form.as_table }}
        </table>
        <p align='center'><input type="submit" value="OK"></p>
    </form>
    
    </div>

    

    {% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/detail.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">

	{% include "navbar.html" %} 
    <div class="container" style="margin-top: 50px;">
        <h1>{{m}}</h1>
        <p>{{d}}</p>
    </div>
    
		{% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/editmatkul.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">

    {% include "navbar.html" %}
    <div class="container" style="margin-top: 50px;" >
    <h2 align='center'>Tambah Matkul</h2>
    <form action="/edit" method="post">
        {% csrf_token %}
        <table align="center">
        {{ form.as_table }}
        </table>
        <p align="center"><input type="submit" value="OK" ></p>
    </form>
    </div>

    

    {% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

main/templates/main/kegiatan.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">
    
    {% include "navbar.html" %} 
    <div class="container" style="margin-top: 50px;">
    {% for data in kegiatan %}
    <br><br>
    <h2>{{data.nama_kegiatan}}</h2>
    <p>Deskripsi : {{data.deskripsi_kegiatan}}</p>
    <p>Peserta:</p>
    <ul style="list-style-type:circle;">
    {% for orang in orang %}
    {% if orang.nama_kegiatan == data %}
    <li style="float:none;">{{orang.nama_orang}}</li>
    {% endif %}
    {% endfor %}
    </ul>
    <br><a class="btn-link" href={% url 'main:daftar' data.id %} >Daftar</a>
    {% endfor %}
    </div>
	{% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/success.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">

    {% include "navbar.html" %}
    <div class="container" style="margin-top: 50px;">
    <h1 align="center">Success</h1>

    
    </div>
    {% include "footer.html" %}
		
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>